spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phoneShop
    username: root
    password: piseth123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect


