spring:
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:postgresql://localhost:5432/phoneshop
    username: sa
#    username: postgres
    password:
#    password: Sophat&postgre22

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        hibernate:
#          dialect: org.hibernate.dialect.H2Dialect
#          dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      fail-on-empty-beans: false


